###
GET http://localhost:8000/companies

###
POST http://localhost:8000/company
Content-Type: application/json

{
    "name": "QOS IT - SOLUCOES EM SERVICOS DE TECNOLOGIA LTDA",
    "cnpj": 21950170000107,
    "phone": 4140637066,
    "email": "contato@qosit.com.br",
}

###
POST http://localhost:8000/company
Content-Type: application/json

{
    "name": "JOAO DA ESQUINA LTDA",
    "cnpj": 23123654000178,
    "phone": 4133322223,
    "email": "contato@joaodaesquina.com.br",
}