###
GET http://localhost:8000/companies

###
POST http://localhost:8000/company
content-type: application/json

{
    "namse": "QOS IT - SOLUCOES EM SERVICOS DE TECNOLOGIA LTDA",
    "cnpj": 21950170000107,
    "phone": 4140637066,
    "email": "contato@qosit.com.br"
}

###
POST http://localhost:8000/company
content-type: application/json

{
    "name": "ESCOLA RAIO DE SOL LTDA",
    "cnpj": "21123456000798",
    "phone": "41999998888",
    "email": "contato@escolaraiodesol.com.br"
}